[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "paxjaxlib"
version = "0.2.1"
description = "A simple neural network implementation using JAX, made for educational purposes"
readme = "README.md"
requires-python = ">=3.13"
license = { text = "MIT" }
authors = [
    { name = "Igor Beketov", email = "paxamans@gmail.com" }
]
keywords = ["neural network", "deep learning", "jax"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "jax==0.8.1",
    "jaxlib==0.8.1",
    "numpy==2.3.5",
    "optax==0.2.6",
]

[project.urls]
Homepage = "https://github.com/paxamans/paxjaxlib"

[tool.setuptools.packages.find]
where = ["src"]

[project.optional-dependencies]
dev = [
    "pytest==9.0.1",
    "ruff==0.14.5",
    "mypy==1.18.2",
    "pre-commit==4.4.0",
]
torch = [
    "torch>=2.0.0",
]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I", "B"]
ignore = []
[tool.ruff.lint.isort]
known-first-party = ["paxjaxlib"]

[tool.mypy]
python_version = "3.13"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
ignore_missing_imports = true
explicit_package_bases = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
